baseURL = "https://weriomat.com"
title = "weriomat"
theme = "hugo-coder"
languageCode = 'en-us'
defaultContentLanguage = "en"
paginate = 6
enableEmoji = true

[markup.highlight]
noClasses = false
style = "catppuccin-mocha"

[params]
# TODO: here
author = "WERIOMAT"
# license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
description = "Weriomat's website"
keywords = "blog,developer,personal,nixos,selfhosting,rust"
info = ["German student and sysadmin", "average nixos enjoyer"]
# info = ["sysadmin", "nixos", "student"]
# avatarURL = "images/avatar.jpg"
dateFormat = "2 January , 2006"
since = 2024
# Git Commit in Footer, uncomment the line below to enable it
# commit = "https://github.com/luizdepra/hugo-coder/tree/"
# TODO: here
# faviconSVG = "/img/favicon.svg"
# favicon_32 = "/img/favicon-32x32.png"
# favicon_16 = "/img/favicon-16x16.png"

colorScheme = "dark"
hideColorSchemeToggle = true # hide theme toggle
maxSeeAlsoItems = 5
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []
customJS = []
# Custom remote JS files
customRemoteJS = []

# TODO: here
# If you want to use Matomo(https://matomo.org) for analytics, add this section
# [params.matomo]
# siteID = "ABCDE" # Default value is "1", overwrite this if you are cloud-hosting
# serverURL = "analytics.example.com" # For cloud-hosting, use provided URL, e.g. example.matomo.cloud

# If you want to use plausible(https://plausible.io) for analytics, add this section
# [params.plausibleAnalytics]
# domain = "example.com"
# serverURL = "analytics.example.com" # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
# outboundLinksTracking = true
# fileDownloadsTracking = true

# TODO: here
# If you want to implement a Content-Security-Policy, add this section
# https://web.dev/articles/csp
# [params.csp]
# childsrc = ["'self'"]
# fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
# formaction = ["'self'"]
# framesrc = ["'self'", "https://www.youtube.com"]
# imgsrc = ["'self'"]
# objectsrc = ["'none'"]
# stylesrc = [
#   "'self'",
#   "'unsafe-inline'",
#   "https://fonts.googleapis.com/",
#   "https://cdn.jsdelivr.net/",
# ]
# scriptsrc = [
#   "'self'",
#   "'unsafe-inline'",
#   "https://www.google-analytics.com",
#   "https://cdn.jsdelivr.net/",
# ]
# prefetchsrc = ["'self'"]
# # connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
# connectsrc = ["'self'", "https://www.google-analytics.com"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/weriomat/"

[[params.social]]
name = "Gitlab"
icon = "fa-brands fa-gitlab fa-2x"
weight = 2
url = "https://git.weriomat.com/"

[[params.social]]
name = "Mail"
icon = "fa-solid fa-envelope fa-2x"
weight = 3
url = "mailto:engel@weriomat.com"


# [[params.social]]
# name = "RSS"
# icon = "fa-solid fa-rss fa-2x"
# weight = 6
# url = "https://myhugosite.com/index.xml"
# rel = "alternate"
# type = "application/rss+xml"

[languages.en]
languageName = ":uk:"

# [[languages.en.menu.main]]
# name = "About"
# weight = 1
# url = "about/"

# [[languages.en.menu.main]]
# name = "Blog"
# weight = 2
# url = "posts/"

# [[languages.en.menu.main]]
# name = "Projects"
# weight = 3
# url = "projects/"

# [[languages.en.menu.main]]
# name = "Contact me"
# weight = 5
# url = "contact/"
